### ISSUE TITLE
Delete master branch on GitHub?

### ISSUE THREAD

**Issue by The-Compiler** [gforcada/flake8-builtins#118]
It looks like the `master` branch on GitHub still exists. Thus, links like e.g. https://github.com/gforcada/flake8-builtins/blob/master/CHANGES.rst point to an outdated version of the file.

When deleting it, GitHub will instead automatically redirect such links from master to main and show a banner about the move.

**Comment by The-Compiler** [comment]
Same thing for `flake8-deprecated` as well FWIW. Let me know if I should rather open a separate issue there.

**Comment by gforcada** [comment]
Thanks for pointing it out! 😊  I fixed it on all my `flake8` plugins 🎉
