### ISSUE TITLE
A005 does not fire for packages

### ISSUE THREAD

**Issue by kasium** [gforcada/flake8-builtins#124]
Not sure if this intended, but A005 does not fire for packages (folders) shadowing stdlib modules. So, `socket/__init__.py` will not lead to an flake8 error

**Comment by asfaltboy** [comment]
Nice find @kasium, it's an oversight on my end as I didn't test this scenario when submitting the original PR for the rule (see #121).

It seems flake8's iterator interface currently only runs for modules (.py files) and does not run for directories. But, I think we can look for `__init__.py` modules, that have a parent dir called the same as a built-in. I'll open a quick PR

**Comment by kasium** [comment]
Thanks a lot!

**Comment by gforcada** [comment]
@asfaltboy @kasium `flake8-builtins==2.5.0` is out 🎩 🐰 ✨
