### ISSUE TITLE
Split A002 to distinguish between parameter usage and definition?

### ISSUE THREAD

**Issue by mccalluc** [gforcada/flake8-builtins#13]
I've just added this to my project, and it has caught a number of my mistakes... but it's also catching places where outside libraries chose kwargs that shadow builtins, which doesn't worry me as much: I would probably ignore these. Both cases raise `A002`: Would it make sense to split this into two categories?

I can try to make a PR, but I wanted to make sure this is a reasonable direction, first.

**Comment by mccalluc** [comment]
[Made a fork](https://github.com/gforcada/flake8-builtins/compare/master...mccalluc:mccalluc/distinguish-kwarg-def-and-usage?expand=1), and thought it would be easy, but haven't been able to reproduce the [failure I had in my other project](https://travis-ci.org/refinery-platform/heatmap-scatter-dash/builds/344077196?utm_source=github_status&utm_medium=notification): ie, The behavior here is actually what I want, with only the definition case triggering the message, not the usage case. 

I'll ask around the office for a review: Hopefully I'm doing something dumb.

**Comment by gforcada** [comment]
@mccalluc thanks for using the plugin and spending the time to report and actually even cook a patch!

Yes, it does make sense, one one case (where you define) you have control over the parameters names, on the other one (where you are a mere consumer) you might not be able to change that... Yes, it definitely makes sense to me: :+1: 

As for your patch, might it be that although you split the message into two, on the code you are always calling the same?

**Comment by mccalluc** [comment]
Sorry to drop the ball here: coming back to it, I can see that I was misinterpreting the output, and the behavior has been what I wanted all along. Basically, it complained about something like
```python
foo(min=min)
```
but not because of the first `min`, but because I chose to use a built-in for a variable.

Closing. Sorry for the bother.

**Comment by mccalluc** [comment]
... but in the process of exploring this, did tweak the `assert_codes` to give me all the mismatches in a comparison, and not just the first: If it's any use to you, great. Thanks again for making this.
```python
    def assert_codes(self, returns, codes):
        if sys.version_info >= (3, 2):
            return_codes = [r[2].split(' ')[0] for r in returns]
            self.assertCountEqual(return_codes, codes)
        else:
            # The same check, but only reports first mismatch
            for item, code in zip(returns, codes):
                self.assertTrue(item[2].startswith(code + ' '))
```
