### ISSUE TITLE
Remove '_' from the builtins list

### ISSUE THREAD

**Issue by sobolevn** [gforcada/flake8-builtins#25]
After upgrading to the latest version, I have faced this issue:

```
/Users/.../user_details_step.py:3:1: A001 "_" is a python builtin and is being shadowed, 
consider renaming the variable
```

But `_` is a common name for unused variables, I think it is not right to annotate them with `# noqa`.

**Comment by gforcada** [comment]
@sobolevn thanks for the report! I'm quite puzzeld on seeing this builtin, which python version are you using? :thinking:

**Comment by sobolevn** [comment]
I am using this template: https://github.com/wemake-services/wemake-django-template
It comes with `python 3.6.5`. 

But, I know that `django` does something with the `_`.

**Comment by gforcada** [comment]
@sobolevn I can not reproduce this on a plain python 3.6:

```
import inspect
import builtins
builtins_list = sorted([x[0] for x in inspect.getmebers(builtins)])
print(builtins_list)
```

I don't have ``_`` on that list. Is django somehow modifying the builtins? that could be quite surprising...

**Comment by sobolevn** [comment]
Yeap, `django` modifies this value. That happens because in some historical version of `python` it was possible to use `_` as some magic value (I am not sure about the exact implementation). 

We are using `django<2.0`.

**Comment by gforcada** [comment]
Fixed in master. I will release a new version shortly.
