### ISSUE TITLE
Issues with detecting shadowed builtins in many places

### ISSUE THREAD

**Issue by The-Compiler** [gforcada/flake8-builtins#29]
I just upgraded to v1.2, and I feel like it's generating way too many false-positives.

First of all: I haven't thought about the full list of cases detected in the changelog yet, but in general, every of those cases should get a dedicated error code, so it's easy to silence a given kind of warning via flake8 if it's a hindrance for some projects.

What is the problem in my case specifically is class methods: For example, if I want to extend Python's `logging` module, I'll need to subclass things from there and override methods called `filter` or `format`.

I'd even go further and argue class methods shouldn't be checked at all by default - it's way too likely to bring up issues which can't be fixed, and the name is only shadowed in the class body, where's typically not any code other than function/variable definitions at all.

**Comment by The-Compiler** [comment]
Looks like this was mostly taken care of in #28, but maybe it'd make sense to make them more fine-grained anyways?

**Comment by gforcada** [comment]
@The-Compiler first of all, sorry for the silence, I'm quite busy recently and only have "bursts" of time to dedicate to it :bowing_man: 

Adding more error codes, one for each case would not be a problem, now that I landed some of the changes (check 1.4.0 version just released) it would be a good idea. It will have to be a 2.0 release though, as it will break others assumptions.

Is that still something you would need/desire, or with #28 it is largely mitigated?

We could go one step further and check, on methods, if the parent class is overriding a builtin and then silence any method check. Would that make sense? :thinking:
