### ISSUE TITLE
A way to disable errors for class attributes

### ISSUE THREAD

**Issue by karamanolev** [gforcada/flake8-builtins#3]
I find this plugin very useful, especially for module-level globals, function arguments, variables, etc., but class attributes are really getting in the way. Can you add a configuration option to disable the errors just for that? There are a bunch of legitimate cases where we have class attributes names that are builtins:

- Django manage.py commands have a standard help attribute to provide command line help.
- django-rest-framework serializers need to serializer the id attribute of a Django model, so naturally the attribute is called id.
- Django models can have id/help/etc. fields that then go into the DB. Access to them is always scoped within the model and while id is a builtin, there is no such builtin as <model instance>.id.

**Comment by karamanolev** [comment]
Implement in #4 by simply moving it to a separate error code, which can then be ignored in the flake8 config.

**Comment by gforcada** [comment]
@karamanolev please try the new 0.4 version and report back. Thanks for providing the patch!!

**Comment by karamanolev** [comment]
@gforcada Thanks for the merge. We've now switched back from my fork to the pypi version and it's working just fine.
