### ISSUE TITLE
noqa does not ignore the error

### ISSUE THREAD

**Issue by cleder** [gforcada/flake8-builtins#38]
In version 1.4.1:
`def id(self):  # noqa: D102, A003` 
raises a flake8 violation although it is explicitly ignored.
`A003 "id" is a python builtin, consider renaming the class attribute`

**Comment by gforcada** [comment]
@cleder I'm happy to report that with a newer version of flake8, or flake8-builtins it should be working. I tested it myself now with python 3.10, flake8-builtins 2.1.0 (just released!) and flake8 5.0.4 and it works 🎉 

If you still have problems, please feel free to re-open the issue, but please provide the version triple: python, flake8 and flake8-builtins versions 😄
