### ISSUE TITLE
Add flake-job to CI

### ISSUE THREAD

**Issue by Bengt** [gforcada/flake8-builtins#47]
To test the code against the latest released version of `flake-builtins` and demonstrate its usage.

**Comment by gforcada** [comment]
@Bengt thanks for taking the time to create the issue :sparkles: 

Would you mind to explain a bit more what you mean? :thinking: you want another job on the travis CI matrix so that it runs flake8-builitins against this repo? :thinking: 

While that would be a good idea, I miss the point of the `demonstrate its usage` part.

**Comment by Bengt** [comment]
Hi, @gforcada!

Thanks for thinking about this.

Yes, I mean checking this repo against itself.

On the one hand this would assure that the code quality of this repo reaches a certain level. On the other hand this demonstrate the applicability of the package in a real software project. People who want to follow this example could copy your Travis matrix definition to theirs in the certainty that the commands work in a realistic environment. So that would be a good starting point.

**Comment by gforcada** [comment]
With #85 I think we are doing enough QA on the code, if you still think we should do more, please re-open the issue 😄

**Comment by Bengt** [comment]
Hi, @gforcada! I am happy to see that you picked up GitHub actions for this project. As far as I can see, you are not ["eating your own dog food"](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) by using your own linter, though. The workflow includes flake8, but without flake8-builtins:

https://github.com/gforcada/flake8-builtins/blob/master/.github/workflows/testing.yml#L50
