### ISSUE TITLE
Builtins as class attrs

### ISSUE THREAD

**Issue by dmitry-saritasa** [gforcada/flake8-builtins#48]
```
class StudentListSerializer(serializers.ModelSerializer):
    id = serializers.IntegerField()
    username = serializers.CharField()
    email = serializers.CharField()
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    date_joined = serializers.CharField()
    avatar = S3DirectUploadURLField()
```

The plugin will alarm

```
apps/users/api/student/serializers.py:19:5: A003 "id" is a python builtin, consider renaming the class attribute
```
is there a configuration option to prevent checking for built-ins for class attrs?

Thanks,
Dmitry

**Comment by gforcada** [comment]
@dmitry-saritasa hi, thanks for using and reporting about `flake8-builtins`!

Yes, there is a way to make `flake8` not report about such errors: all flake8 error messages have a unique identifier which you can provide it to flake8 via the `ignore` configure option. Once you do that, `flake8` will no longer warn you about those errors.

For this specific case the error code is `A003` as you can spot at the beginning of the error message.

I hope this fixes your problem, for that I'm closing this issue. Please re-open if there is something else that might still need some more clarification or behavior being changed in `flake8-builtins` :+1:
