### ISSUE TITLE
Names that use `AnnAssign` are not supported

### ISSUE THREAD

**Issue by sobolevn** [gforcada/flake8-builtins#49]
Reproduction: 
1. `echo 'list: int = 1' > ex.py`
2. `flake8 ex.py`

It exists with status code `0`.

I expect it to work the same as `list = 1` which produces:

```
» flake8 ex.py 

ex.py

  1:1      A001  "list" is a python builtin and is being shadowed, consider renaming the variable
  list = 1
  ^
```

The problem is in this line: https://github.com/gforcada/flake8-builtins/blob/master/flake8_builtins.py#L81 Because it does not check `ast.AnnAssign`

**Comment by sobolevn** [comment]
Related https://github.com/wemake-services/wemake-python-styleguide/issues/1138

**Comment by gforcada** [comment]
Right, I hope to have the time in the near future, but so far, does not look promising, PR are always welcome :rainbow:

**Comment by sobolevn** [comment]
@gforcada will do if you promise me to release it after that 🙂 

I am building https://github.com/wemake-services/wemake-python-styleguide/milestone/10 and it is going to be released soon. And I want to have this feature on board (I use `flake8-builtins` as a dependency)

**Comment by gforcada** [comment]
@sobolevn that's a deal then :)
