### ISSUE TITLE
Walrus operator is not supported

### ISSUE THREAD

**Issue by sobolevn** [gforcada/flake8-builtins#50]
There are several things to add:

1. `ast.NamedExpr` support
2. `python3.8` to the test case
3. `python3.8` classifiers
4. Specific tests for cases like `(list := 1)`

Related https://github.com/wemake-services/wemake-python-styleguide/issues/1138

**Comment by gforcada** [comment]
@sobolevn would you have the time to work on it, or is a whislist of what you would like others to do? :thinking: :smile: 

Everything on the list sound sensible to me

**Comment by sobolevn** [comment]
The same as #49 👍
