### ISSUE TITLE
Dual license

### ISSUE THREAD

**Issue by sobolevn** [gforcada/flake8-builtins#51]
There's a problem: you have two licenses for this project.
- https://github.com/gforcada/flake8-builtins/blob/2d987ecff29b28d7d7e0a6a6f8402f4d1cd3262b/LICENSE
- https://github.com/gforcada/flake8-builtins/blob/2d987ecff29b28d7d7e0a6a6f8402f4d1cd3262b/LICENSE.rst

My guess is that `LICENSE.rst` is not required.

**Comment by gforcada** [comment]
Thanks I did not notice, and it is since the first day :man_facepalming:
