### ISSUE TITLE
Concise Warnings

### ISSUE THREAD

**Issue by GammaGames** [gforcada/flake8-builtins#61]
I think having a flag to enable shorter warning messages would be nice. I am using vscode and the warnings are extremely long:

![image](https://user-images.githubusercontent.com/7832163/81203852-a7641d80-8f85-11ea-8568-27c4cf1df143.png)
![image](https://user-images.githubusercontent.com/7832163/81203808-9adfc500-8f85-11ea-812a-612793d01fad.png)

Something like `variable "max" is shadowing a python builtin` would be plenty to convey the same meaning and cut down the length of the warning by almost half and changing the argument message to `argument "object" is shadowing a python builtin` would make it 50 characters shorter

**Comment by gforcada** [comment]
As long as the error message is conveyed, I'm fine changing wordings, I'm no native English speaker, so there is plenty of room for improvement :+1: 

Would you be up to create a merge request for it? :slightly_smiling_face:

**Comment by GammaGames** [comment]
Sure, I'll take some time to make the PR hopefully sometime in the next week. Thank you!
