### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by MartinThoma** [gforcada/flake8-builtins#64]
The badge in the readme / on PyPI says that the build is failing

**Comment by gforcada** [comment]
Right, and the link points to a fork of this repository, I'm a bit confused on that.

I can do a dummy commit here and see if that fixes it :thinking: 

Thanks for reporting it! :100:

**Comment by gforcada** [comment]
And now is fixed :)

**Comment by MartinThoma** [comment]
Thank you :-)
