### ISSUE TITLE
test_exception_py2 trigger an exception with python 3.9.2

### ISSUE THREAD

**Issue by j-rivero** [gforcada/flake8-builtins#69]
While packaging the software for Debian I found that one of the test triggers a real exception. Environment is Debian Sid with  python version is 3.9.2.

```bash
test_with_statement_unpack_on_list (run_tests.TestBuiltins) ... ok
test_with_statement_unpack_star (run_tests.TestBuiltins) ... ok

======================================================================
ERROR: test_exception_py2 (run_tests.TestBuiltins)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jrivero/code/debian/flake8-builtins/run_tests.py", line 329, in test_exception_py2
    tree = ast.parse(
  File "/usr/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 3
    except Exception, int:
                    ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 60 tests in 0.018s

FAILED (errors=1)
```

Please note that I'm running the test suite with the following patch (since hypothesmith is not in Debian). I'm not sure that the error is related:
```diff
diff --git a/run_tests.py b/run_tests.py
index 3ee8091..a0594e6 100644
--- a/run_tests.py
+++ b/run_tests.py
@@ -16,7 +16,6 @@ except ImportError:
 if sys.version_info >= (3, 6):
     from hypothesis import given
     from hypothesis import reject
-    import hypothesmith
 
 
 class TestBuiltins(unittest.TestCase):
@@ -570,7 +569,6 @@ class TestBuiltins(unittest.TestCase):
 
 
 if sys.version_info >= (3, 6):
-    @given(source_code=hypothesmith.from_grammar())
     def test_builtin_works_on_many_examples(source_code):
         try:
             source = source_code.encode('utf-8-sig')
```
Thanks.

**Comment by gforcada** [comment]
Hi! sorry for the lateness on my reply! 😱 😓 

In theory not, the problem should not be from your patch... but it is interesting because this test is guarded with a condition to only run it on python lower than 3.0, so why it is executed on python 3.9 ? 🤔

**Comment by gforcada** [comment]
I installed pytest, flake8 and hypotesis (and hypothesmith as well, but you patch it away) in a python 3.9 virtual environment and tests run successful and one is skipped, this one that fails for you...

Might it be that as you did not have a virtual environment enabled, the default python interpreter is still python 2 and that's what `sys.version_info` gets, although you run it on python 3.9 ? 🤔

**Comment by j-rivero** [comment]
> Hi! sorry for the lateness on my reply! scream sweat

No worries.
 
> In theory not, the problem should not be from your patch... but it is interesting because this test is guarded with a condition to only run it on python lower than 3.0, so why it is executed on python 3.9 ? thinking

Ouk, you are right. I just removed the patch and the whole CI is just fine https://salsa.debian.org/jrivero-guest/flake8-builtins/-/pipelines/292122.

Not sure what I broke during my works but I think we are good.

Thanks! closing.
