### ISSUE TITLE
Bugbear and builtins both using B001 

### ISSUE THREAD

**Issue by cas--** [gforcada/flake8-builtins#7]
I have not tested the consequences of this but I found googling for B001 that you both picked the same B prefix code in March 2016!

https://github.com/PyCQA/flake8-bugbear#list-of-warnings

**Comment by ambv** [comment]
As bugbear is an official PyCQA plugin, it would be probably best for the author to change the code used by `flake8-builtins`.

**Comment by gforcada** [comment]
@ambv I, as the author, wouldn't mind changing it to X, Y, Z or whatever word, problem is as soon as you get more than 26 plugins... what should we do? https://pypi.org/search/?q=flake8 already reports 423 projects... Is that something that flake8 has already thought about?

I've seen that a plugin can claim not only a word but part of a letter as well, i.e. ``B0`` (giving you B001 to B099`` or ``B00`` which gives only B001 to B009), so maybe bugbear could restrict itself a little bit as well...

Anyway, I will make a major breaking release of builtins plugin and I will pick up... ``A`` for example.

**Comment by gforcada** [comment]
@ambv I, as the author, wouldn't mind changing it to X, Y, Z or whatever word, problem is as soon as you get more than 26 plugins... what should we do? https://pypi.org/search/?q=flake8 already reports 423 projects... Is that something that flake8 has already thought about?

I've seen that a plugin can claim not only a word but part of a letter as well, i.e. ``B0`` (giving you B001 to B099`` or ``B00`` which gives only B001 to B009), so maybe bugbear could restrict itself a little bit as well...

Anyway, I will make a major breaking release of builtins plugin and I will pick up... ``A`` for example.

**Comment by gforcada** [comment]
@cas-- @ambv flake8-builtins 1.0 is released with the error codes changed to ``A00X``.
