### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by steakhutzeee** [gforcada/flake8-builtins#77]
Hi,

i'm trying to use builtins on VSCode without success. Using Python 3.10. Is this version not supported yet?

Thanks!

**Comment by gforcada** [comment]
Hi @steakhutzeee thanks for using `flake8-builtins` and taking the time to report your findings with it.

It might be that indeed it does not work, what exact traceback/error do you see that leads you to this idea? 🤔

**Comment by steakhutzeee** [comment]
I installed it and tried to add some variables names that should be seen by flake8-builtins, using VSCodium.

My settings are:

```
--select=C,C4,E,E8,F,W,B,B902,B950,N,A
--extend-ignore=E203, E501
--max-line-length=88
--max-complexity=10
```

**Comment by gforcada** [comment]
@steakhutzeee a few minutes ago I released flake8-builtins __2.1.0__ with python official 3.10 support.
