### ISSUE TITLE
doesn't work with pyproject-flake8

### ISSUE THREAD

**Issue by delgod** [gforcada/flake8-builtins#78]
The plugin doesn't check code issues if flake8 runs via [pflake8](https://github.com/csachs/pyproject-flake8).
Other flake8 plugins (like flake8-copyright, flake8-docstrings, pep8-naming) work fine.

**Comment by gforcada** [comment]
Hi @delgod ! thanks for taking the time report about your usage with flake8-builtins! 😄 

I'm sorry that you are having a problem with it though... I myself never heard of `pflake8`.

I see that there is still no official release of `pflake8` on PyPI, would you mind describing the steps you took to install it and what's not working when running it together with `flake8-builtins`?

**Comment by gforcada** [comment]
@delgod friendly ping 😄 I'm closing the issue, re-open if you are still interested in getting `flake8-builtins` to work with `pflake8` and it is still not working fine 🍀
