### ISSUE TITLE
Feature request: Skip class attributes

### ISSUE THREAD

**Issue by shangxiao** [gforcada/flake8-builtins#93]
Nice idea, I wish I could use it on my current project however there are a lot of class attributes (methods and variables) that are deemed acceptable to use builtin names.

**Comment by gforcada** [comment]
@shangxiao hi! 👋🏾 thanks for using `flake8-builtins` and spending the time to report your findings with it! 👍🏾 

If you look at the output from `flake8` you should see that these class attributes are marked with `A003` code, is it?

Then you could tell `flake8`, via [its configuration](https://flake8.pycqa.org/en/5.0.4/user/configuration.html), or on the command line, to [ignore this specific error code](https://flake8.pycqa.org/en/5.0.4/user/violations.html).

If I missed your point, which happens quite frequently, please re-open the issue with some code example, the output you get and which error reported by `flake8-builtins` you would want to get ignored 😄
